#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-aircompressor
Version  : 0.10
Release  : 1
URL      : https://github.com/airlift/aircompressor/archive/0.10.tar.gz
Source0  : https://github.com/airlift/aircompressor/archive/0.10.tar.gz
Source1  : https://repo1.maven.org/maven2/io/airlift/aircompressor/0.10/aircompressor-0.10.jar
Source2  : https://repo1.maven.org/maven2/io/airlift/aircompressor/0.10/aircompressor-0.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-aircompressor-data = %{version}-%{release}

%description
# Compression in pure Java
[![Maven Central](https://img.shields.io/maven-central/v/io.airlift/aircompressor.svg?label=Maven%20Central)](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.airlift%22%20AND%20a%3A%22aircompressor%22)
[![Build Status](https://travis-ci.org/airlift/aircompressor.svg?branch=master)](https://travis-ci.org/airlift/aircompressor)

%package data
Summary: data components for the mvn-aircompressor package.
Group: Data

%description data
data components for the mvn-aircompressor package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10/aircompressor-0.10.jar
/usr/share/java/.m2/repository/io/airlift/aircompressor/0.10/aircompressor-0.10.pom
